### ISSUE TITLE
Template without single screenshot 🤦‍♂️

### ISSUE THREAD

**Issue by TobbyReign** [torrix/laravel-uikit#6]
Why. Just why.

**Comment by mattfletcher** [comment]
> Why. Just why.

Because I'm just one guy who built this in his spare time to scratch an itch. 

There was originally a screenshot referenced from a remote URL, and that screenshot got wiped during a server move. I've changed it to be built into the repo now.

Thanks for flagging this with me. I hope you enjoy using the package.
